# Default values for wordsmith-another-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cleclerc/wordsmith-another-api
  tag: "{{version}}"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - another-api.staging.wordsmith.beescloud.com
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
